function [points_row, lines] = get_3Dbox(scale)
%KEYPOINT_LIBRARY 이 함수의 요약 설명 위치
%   자세한 설명 위치
    points_row=[scale(1),scale(2),scale(3); ...
                scale(1),scale(2),-scale(3); ...
                scale(1),-scale(2),scale(3); ...
                scale(1),-scale(2),-scale(3); ...
                -scale(1),scale(2),scale(3); ...
                -scale(1),scale(2),-scale(3); ...
                -scale(1),-scale(2),scale(3); ...
                -scale(1),-scale(2),-scale(3)]/2;
    lines = [1,2; 1,3; 1,5; 2,4; 2,6; 3,4; 3,7; 4,8; 5,6; 5,7; 6,8; 7,8]';
end

