function [points_row, lines] = keypoint_library(cls)
%KEYPOINT_LIBRARY 이 함수의 요약 설명 위치
%   자세한 설명 위치
    switch(cls)
        case 0
            scale = [0.16, 0.23, 0.06];
            points_row=[scale(1),scale(2),scale(3); ...
                        scale(1),scale(2),-scale(3); ...
                        scale(1),-scale(2),scale(3); ...
                        scale(1),-scale(2),-scale(3); ...
                        -scale(1),scale(2),scale(3); ...
                        -scale(1),scale(2),-scale(3); ...
                        -scale(1),-scale(2),scale(3); ...
                        -scale(1),-scale(2),-scale(3)]/2;
            lines = [1,2; 1,3; 1,5; 2,4; 2,6; 3,4; 3,7; 4,8; 5,6; 5,7; 6,8; 7,8]';
        case 1
                
            dat = load('F:\hourglasstensorlfow-master-aug\datasets\train_bak\hinter01\cad\cad.mat');
            cad = dat.cad;
            points_row=double(cad.vertices);
%             scale = [0.1, 0.1, 0.1];
%             points_row=[scale(1),scale(2),scale(3); ...
%                         scale(1),scale(2),-scale(3); ...
%                         scale(1),-scale(2),scale(3); ...
%                         scale(1),-scale(2),-scale(3); ...
%                         -scale(1),scale(2),scale(3); ...
%                         -scale(1),scale(2),-scale(3); ...
%                         -scale(1),-scale(2),scale(3); ...
%                         -scale(1),-scale(2),-scale(3)]/2;
            lines = [1,2; 1,3; 1,5; 2,4; 2,6; 3,4; 3,7; 4,8; 5,6; 5,7; 6,8; 7,8]';
        case 4
                
            dat = load('F:\hourglasstensorlfow-master-aug\datasets\train_bak\hinter04\cad\cad.mat');
            cad = dat.cad;
            points_row=double(cad.vertices);
%             scale = [0.1, 0.1, 0.1];
%             points_row=[scale(1),scale(2),scale(3); ...
%                         scale(1),scale(2),-scale(3); ...
%                         scale(1),-scale(2),scale(3); ...
%                         scale(1),-scale(2),-scale(3); ...
%                         -scale(1),scale(2),scale(3); ...
%                         -scale(1),scale(2),-scale(3); ...
%                         -scale(1),-scale(2),scale(3); ...
%                         -scale(1),-scale(2),-scale(3)]/2;
            lines = [1,2; 1,3; 1,5; 2,4; 2,6; 3,4; 3,7; 4,8; 5,6; 5,7; 6,8; 7,8]';
        otherwise
            scale = [0.1, 0.1, 0.1];
            points_row=[scale(1),scale(2),scale(3); ...
                        scale(1),scale(2),-scale(3); ...
                        scale(1),-scale(2),scale(3); ...
                        scale(1),-scale(2),-scale(3); ...
                        -scale(1),scale(2),scale(3); ...
                        -scale(1),scale(2),-scale(3); ...
                        -scale(1),-scale(2),scale(3); ...
                        -scale(1),-scale(2),-scale(3)]/2;
            lines = [1,2; 1,3; 1,5; 2,4; 2,6; 3,4; 3,7; 4,8; 5,6; 5,7; 6,8; 7,8]';
    end
end

